### ISSUE TITLE
qlog-dancer: wasm build fails to compile (f32/f64 type mismatches in web.rs)

### ISSUE THREAD

**Issue by birneee** [cloudflare/quiche#2519]
`wasm-pack build --target=web` in `qlog-dancer/` fails:

```
error[E0308]: mismatched types
   --> qlog-dancer/src/web.rs:740:26
    |
740 |                     end: x_end,
    |                          ^^^^^ expected `Option<f64>`, found `Option<f32>`
    |
    = note: expected enum `std::option::Option<f64>`
               found enum `std::option::Option<f32>`

error[E0308]: mismatched types
   --> qlog-dancer/src/web.rs:763:58
    |
763 |                 Some(ChartInfo::<f32, u64>::with_u64_f32(&chart));
    |                      ----------------------------------- ^^^^^^ expected `RangedCoordf32`, found `RangedCoordf64`
    |                      |
    |                      arguments to this function are incorrect
    |
    = note: expected reference `&plotters::chart::ChartContext<'_, _, plotters::prelude::Cartesian2d<_, RangedCoordf32>>`
               found reference `&plotters::chart::ChartContext<'_, _, plotters::prelude::Cartesian2d<_, RangedCoordf64>>`
```

Bug was introduced by https://github.com/cloudflare/quiche/pull/2386

This was not caught by CI because qlog-dancer is excluded.
