### PR TITLE
qlog: release 0.18.0

### PR DESCRIPTION
**Pull request by estcarisimo**
## qlog 0.18.0

Minor (breaking) release. Bumps `qlog/Cargo.toml` from `0.17.0` to `0.18.0`
and updates the workspace dependency declaration.

### Breaking changes

- `QlogStreamer::new` gained a 7th parameter for the new compression argument
  (introduced in #2444). Callers must pass a compression value:

  ```rust
  // Before
  QlogStreamer::new(qlog_version, title, description, summary, time_ref, vp, writer);
  // After
  QlogStreamer::new(qlog_version, title, description, summary, time_ref, vp, compression, writer);

### CODE REVIEW

**Comment by estcarisimo** [comment]
## CI red is the documented known-issue for releasing local crates

CI's 5 build failures (`quiche`, `quiche_nightly`, `quiche_macos (macos-latest)`, `quiche_ios (x86_64-apple-ios)`, `quiche_windows (x86_64-pc-windows-msvc)`) all hit the same root error in `cargo test`:

```
error[E0277]: the trait bound `QlogCompression: foundations::settings::Settings` is not satisfied
note: there are multiple different versions of crate `foundations` in the dependency graph
  --> foundations-4.5.0/src/settings/mod.rs:344:1 (expected trait)
  --> foundations-5.7.0/src/settings/mod.rs:346:1 (found trait)
```

Root cause: workspace `Cargo.toml` declares `foundations = { version = ">=4,<6" }`. When a path-redirected workspace crate (here, `qlog`) bumps to a version not yet on crates.io, the cargo resolver back-tracks through `foundations` to find a satisfiable graph, picks different versions for different consumers, and the resulting two-version graph breaks the `#[settings]` macro's trait bound.

This is the same class of issue already documented in [stable.yml lines 52-57](https://github.com/cloudflare/quiche/blob/master/.github/workflows/stable.yml#L52-L57):

> NOTE: this is disabled as it fails when building changes that bump version of local crates (e.g. when doing a `qlog` release) that have not been published yet, and we couldn't find a workaround.

The workaround comment is about `cargo package` only, but the same trap hits `cargo test` via the `foundations` version range here.

**The PR itself is correct:** semver-checks confirms qlog 0.17.0 → 0.18.0 is the right (minor / pre-1.0-breaking) bump because `QlogStreamer::new` gained a 7th parameter for the new compression argument. Once this PR merges and qlog 0.18.0 is on crates.io, master's CI will resolve cleanly again.

Requesting a CI-override merge per the documented release procedure.

**Review by LPardue — APPROVED** [review]

**Review by antoniovicente — APPROVED** [review]
